import type { Metadata } from 'next'
import { Header } from './../components/header'
import TransitionPage from './transition'


export const metadata: Metadata = {
  title: 'PROJECT',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <TransitionPage>
          <Header />
          {children}
        </TransitionPage>
      </body>
    </html>
  )
}